---
- name: Clone dotfiles
  git: repo=https://github.com/stevenyap/dotfiles.git dest={{ home_directory }}/.dotfiles force=no update=no

- stat: path={{ home_directory }}/.{{ item }}
  with_items: symlink_dotfiles
  register: dotfiles
  changed_when: false

- name: Remove system dotfiles
  file: path={{ home_directory }}/.{{ item }} state=absent
  with_items: dotfiles.results
  when: not item.stat.islnk

- name: Symlink dotfiles
  file: path={{ home_directory }}/.{{ item }} src={{ home_directory }}/.dotfiles/.{{ item }} state=link 
  with_items: symlink_dotfiles

- name: source .dotfiles/.bash_profile in ~/.bash_profile
  lineinfile: create=yes dest={{ home_directory }}/.bash_profile line="source ~/.dotfiles/.bash_profile"

- name: Clone Vim Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim update=no

- stat: path={{ home_directory }}/.vim/bundle/vim-rails
  register: vim_plugins_installed
  changed_when: false

- name: Install Vim Plugins
  shell: vim +PluginInstall +qall > /dev/null 2>&1
  when: not vim_plugins_installed.stat.exists

- command: gem list
  register: installed_gems
  changed_when: false

- name: Install Gems
  shell: gem install {{ item }} --no-ri --no-rdoc
  with_items: gems
  when: "'{{ item }}' not in installed_gems.stdout"

- name: Symlink custom apps in /Applications folder
  file: path=/Applications/{{ item }} src={{ home_directory }}/.dotfiles/Applications/{{ item }} state=link 
  with_items: apps
