--- # Scripts taken from https://github.com/mathiasbynens/dotfiles/blob/master/.osx
- shell: hostname
  register: hostname
  changed_when: false

- name: Set machine name
  shell: scutil --set HostName {{ machine_name }}
  sudo: true
  when: hostname.stdout != machine_name

- shell: git config --global credential.helper
  register: git_credential_helper
  changed_when: false

- name: Make Git remembers account login
  shell: git config --global credential.helper osxkeychain
  when: git_credential_helper.stdout != 'osxkeychain'

- name: Set non-natural mouse scroll
  osx_defaults: domain=NSGlobalDomain key=com.apple.swipescrolldirection type=bool value=false

- name: Enable tap to click for this user and for the login screen (1/2)
  osx_defaults: domain=com.apple.driver.AppleBluetoothMultitouch.trackpad key=Clicking type=bool value=true state=present

- name: Enable tap to click for this user and for the login screen (2/2)
  osx_defaults: domain=NSGlobalDomain key=com.apple.mouse.tapBehavior type=int value=1

- name: Auto hide the dock
  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true state=present

- shell: defaults read com.apple.dock {{ item }}
  with_items:
    - autohide-delay
    - autohide-time-modifier
    - persistent-apps
  register: com_apple_dock
  changed_when: false

- name: Remove the auto-hiding Dock delay
  shell: defaults write com.apple.dock autohide-delay -float 0
  when: com_apple_dock.results[0].stdout != "0"

- name: Remove the animation when hiding/showing the Dock
  shell: defaults write com.apple.dock autohide-time-modifier -float 0
  when: com_apple_dock.results[1].stdout != "0"

- name: Wipe all (default) app icons from the Dock
  shell: defaults write com.apple.dock persistent-apps -array
  when: com_apple_dock.results[2].stdout != "(\n)"
 
- name: Set the icon size of Dock items to 2 pixels
  osx_defaults: domain=com.apple.dock key=tilesize type=int value=2 state=present

- name: Disable the sound effects on boot
  shell: 'nvram SystemAudioVolume=" "'
  sudo: true

- name: Expand save panel by default (1/2)
  osx_defaults: domain=NSGlobalDomain key=NSNavPanelExpandedStateForSaveMode type=bool value=true

- name: Expand save panel by default (2/2)
  osx_defaults: domain=NSGlobalDomain key=NSNavPanelExpandedStateForSaveMode2 type=bool value=true

- name: Expand print panel by default (1/2)
  osx_defaults: domain=NSGlobalDomain key=PMPrintingExpandedStateForPrint type=bool value=true

- name: Expand print panel by default (2/2)
  osx_defaults: domain=NSGlobalDomain key=PMPrintingExpandedStateForPrint2 type=bool value=true

- name: Save to disk (not to iCloud) by default
  osx_defaults: domain=NSGlobalDomain key=NSDocumentSaveNewDocumentsToCloud type=bool value=false

- name: Disable the "Are you sure you want to open this application?" dialog
  osx_defaults: domain=com.apple.LaunchServices key=LSQuarantine type=bool value=false state=present

- shell: launchctl list
  register: launchctl_list
  changed_when: false

- name: Disable Notification Center and remove the menu bar icon
  shell: launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null
  when: "'notificationcenterui' in launchctl_list.stdout"

- name: Disable smart quotes as they’re annoying when typing code
  osx_defaults: domain=NSGlobalDomain key=NSAutomaticQuoteSubstitutionEnabled type=bool value=false

- name: Disable smart dashes as they’re annoying when typing code
  osx_defaults: domain=NSGlobalDomain key=NSAutomaticDashSubstitutionEnabled type=bool value=false

- name: Set a blazingly fast keyboard repeat rate
  osx_defaults: domain=NSGlobalDomain key=KeyRepeat type=int value=1

- name: Disable auto-correct
  osx_defaults: domain=NSGlobalDomain key=NSAutomaticSpellingCorrectionEnabled type=bool value=false

- name: Ask for password after sleep or screen saver begins
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1 state=present

- name: Ask for password delay to be 15 mins after sleep or screen saver begins
  osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=int value=900 state=present

- name: Finder - show hidden files by default
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present

- name: Finder - show Desktop folder by default
  osx_defaults: domain=com.apple.finder key=NewWindowTarget type=string value="PfDe"  state=present

- name: Finder - show all filename extensions
  osx_defaults: domain=NSGlobalDomain key=AppleShowAllExtensions type=bool value=true

- name: Finder - show status bar
  osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true state=present

- name: Finder - show path bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true state=present

- name: Finder - allow text selection in Quick Look
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true state=present

- name: Finder - Display full POSIX path as Finder window title
  osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle type=bool value=true state=present

- name: Finder - Disable the warning when changing a file extension
  osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=false state=present

- name: Finder - Avoid creating .DS_Store files on network volumes
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true state=present

- name: Finder - Enable snap-to-grid for icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  shell: /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  shell: /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

- name: Finder - Use list view in all Finder windows by default
  osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle type=string value="Nlsv" state=present

- name: Finder - Disable the warning before emptying the Trash
  osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=false state=present

- name: Finder - Expand the following File Info panes - "General", "Open with", and "Sharing & Permissions"
  shell: defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true

- name: TextEdit - Use plain text mode for new documents
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0 state=present

- name: TextEdit - Open files as UTF-8
  osx_defaults: domain=com.apple.TextEdit key=PlainTextEncoding type=int value=4 state=present

- name: TextEdit - Save files as UTF-8
  osx_defaults: domain=com.apple.TextEdit key=PlainTextEncodingForWrite type=int value=4 state=present

- name: TextEdit - Open an empty document by default
  osx_defaults: domain=NSGlobalDomain key=NSShowAppCentricOpenPanelInsteadOfUntitledFile type=bool value=false
