---
- name: Clone dotfiles
  git: repo=https://github.com/stevenyap/dotfiles.git dest={{ home_directory }}/.dotfiles force=no update=no

- stat: path={{ home_directory }}/.gitignore_global
  register: gitignore_global
  changed_when: false

- name: Remove .gitignore_global if it is not a symlink
  file: path={{ home_directory }}/.gitignore_global state=absent
  when: not gitignore_global.stat.islnk

- name: Remove system dotfiles
  file: path={{ home_directory }}/.{{ item }} state=absent
  with_items: symlink_dotfiles

- name: Symlink dotfiles
  file: path={{ home_directory }}/.{{ item }} src={{ home_directory }}/.dotfiles/.{{ item }} state=link 
  with_items: symlink_dotfiles

- name: source .dotfiles/.bash_profile in ~/.bash_profile
  lineinfile: create=yes dest={{ home_directory }}/.bash_profile line="source ~/.dotfiles/.bash_profile"

- name: Clone Vim Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Install Vim Plugins
  shell: vim +PluginInstall +qall > /dev/null 2>&1

- name: Install Gems
  shell: gem install {{ item }} --no-ri --no-rdoc
  with_items:
    - tmuxinator
    - bundler
