---
- name: Symlink Sublime text 3 bin
  file: path=/usr/local/bin/subl src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl state=link 

- stat: path={{ home_directory }}/.ssh
  register: ssh_directory
  changed_when: false

- name: Remove ssh folder if it is a directory
  file: path={{ home_directory }}/.ssh state=absent
  when: not ssh_directory.stat.islnk

- name: Symlink ssh folder to Dropbox
  file: path={{ home_directory }}/.ssh src={{ home_directory }}/Dropbox/.ssh state=link
  when: not ssh_directory.stat.islnk
