---
- name: Make Git remembers account login
  shell: git config --global credential.helper osxkeychain

- stat: path={{ home_directory }}/Library/Fonts/Inconsolata\ for\ Powerline.otf
  register: font
  changed_when: false

- name: Download Inconsolata font and various other fonts
  git: repo=https://github.com/powerline/fonts.git dest={{ tmp_download_folder }}
  when: not font.stat.exists

- name: Install Inconsolata font and various other fonts
  shell: "{{ tmp_download_folder }}/install.sh"
  when: not font.stat.exists

- name: Remove downloaded fonts
  file: path={{ tmp_download_folder }} state=absent
  when: not font.stat.exists

- name: Clone dotfiles
  git: repo=https://github.com/stevenyap/dotfiles.git dest={{ home_directory }}/.dotfiles force=no update=no

- stat: path={{ home_directory }}/.gitignore_global
  register: gitignore_global
  changed_when: false

- name: Remove .gitignore_global if it is not a symlink
  file: path={{ home_directory }}/.gitignore_global state=absent
  when: not gitignore_global.stat.islnk

- name: Remove system dotfiles
  file: path={{ home_directory }}/.{{ item }} state=absent
  with_items: symlink_dotfiles

- name: Symlink dotfiles
  file: path={{ home_directory }}/.{{ item }} src={{ home_directory }}/.dotfiles/.{{ item }} state=link 
  with_items: symlink_dotfiles

- name: source .dotfiles/.bash_profile in ~/.bash_profile
  lineinfile: create=yes dest={{ home_directory }}/.bash_profile line="source ~/.dotfiles/.bash_profile >> ~/.bash_profile"

- name: Clone Vim Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Install Vim Plugins
  shell: vim +PluginInstall +qall > /dev/null 2>&1

- name: Install Gems
  shell: gem install {{ item }} --no-ri --no-rdoc
  with_items:
    - tmuxinator
    - bundler

- name: Symlink Sublime text 3 bin
  file: path=/usr/local/bin/subl src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl state=link 

- shell: hostname
  register: hostname
  changed_when: false

- name: Set machine name
  shell: scutil --set HostName {{ machine_name }}
  sudo: true
  when: hostname.stdout != machine_name

- name: Set non-natural mouse scroll
  shell: defaults write -g com.apple.swipescrolldirection -bool FALSE

- name: Show all hidden files
  shell: defaults write com.apple.finder AppleShowAllFiles TRUE
