---
# Scripts taken from https://github.com/mathiasbynens/dotfiles/blob/master/.osx
- shell: hostname
  register: hostname
  changed_when: false

- name: Set machine name
  shell: scutil --set HostName {{ machine_name }}
  sudo: true
  when: hostname.stdout != machine_name

- name: Make Git remembers account login
  shell: git config --global credential.helper osxkeychain

- name: Set non-natural mouse scroll
  shell: defaults write NSGlobalDomain com.apple.swipescrolldirection -bool FALSE

- name: Enable tap to click for this user and for the login screen (1/2)
  osx_defaults: domain=com.apple.driver.AppleBluetoothMultitouch.trackpad key=Clicking type=bool value=true state=present

- name: Enable tap to click for this user and for the login screen (2/2)
  shell: defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  shell: defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

- name: Auto hide the dock
  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true state=present

- name: Remove the auto-hiding Dock delay
  shell: defaults write com.apple.dock autohide-delay -float 0

- name: Remove the animation when hiding/showing the Dock
  shell: defaults write com.apple.dock autohide-time-modifier -float 0

- name: Wipe all (default) app icons from the Dock
  shell: defaults write com.apple.dock persistent-apps -array
 
- name: Set the icon size of Dock items to 2 pixels
  osx_defaults: domain=com.apple.dock key=tilesize type=int value=2 state=present

- name: Disable the sound effects on boot
  shell: 'nvram SystemAudioVolume=" "'
  sudo: true

- name: Expand save panel by default
  shell: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
  shell: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

- name: Expand print panel by default
  shell: defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
  shell: defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

- name: Save to disk (not to iCloud) by default
  shell: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

- name: Disable the "Are you sure you want to open this application?" dialog
  osx_defaults: domain=com.apple.LaunchServices key=LSQuarantine type=bool value=false state=present

- name: Disable Notification Center and remove the menu bar icon
  shell: launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

- name: Disable smart quotes as they’re annoying when typing code
  shell: defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

- name: Disable smart dashes as they’re annoying when typing code
  shell: defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

- name: Set a blazingly fast keyboard repeat rate
  shell: defaults write NSGlobalDomain KeyRepeat -int 1

- name: Disable auto-correct
  shell: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

- name: Ask for password after sleep or screen saver begins
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1 state=present

- name: Ask for password delay to be 0 after sleep or screen saver begins
  osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=int value=0 state=present

- name: Finder - show hidden files by default
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present

- name: Finder - show all filename extensions
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Finder - show status bar
  osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true state=present

- name: Finder - show path bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true state=present

- name: Finder - allow text selection in Quick Look
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true state=present

- name: Finder - Display full POSIX path as Finder window title
  osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle type=bool value=true state=present

- name: Finder - Disable the warning when changing a file extension
  osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=false state=present

- name: Finder - Avoid creating .DS_Store files on network volumes
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true state=present

- name: Finder - Enable snap-to-grid for icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  shell: /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  shell: /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

- name: Finder - Use list view in all Finder windows by default
  osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle type=string value="Nlsv" state=present

- name: Finder - Disable the warning before emptying the Trash
  osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=false state=present

- name: Finder - Expand the following File Info panes - "General", "Open with", and "Sharing & Permissions"
  shell: defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true

- name: Use plain text mode for new TextEdit documents
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0 state=present

- name: Open files as UTF-8 in TextEdit
  osx_defaults: domain=com.apple.TextEdit key=PlainTextEncoding type=int value=4 state=present

- name: Save files as UTF-8 in TextEdit
  osx_defaults: domain=com.apple.TextEdit key=PlainTextEncodingForWrite type=int value=4 state=present
