---
- stat: path={{ home_directory }}/.ssh
  register: ssh_directory
  changed_when: false

- name: Remove ssh folder if it is a directory
  file: path={{ home_directory }}/.ssh state=absent
  when: ssh_directory.stat.islnk is defined and ssh_directory.stat.islnk == False

- name: Symlink ssh folder to Dropbox
  file: path={{ home_directory }}/.ssh src={{ home_directory }}/Dropbox/secrets/.ssh state=link

- stat: path={{ home_directory }}/.aws
  register: aws_directory
  changed_when: false

- name: Remove aws folder if it is a directory
  file: path={{ home_directory }}/.aws state=absent
  when: aws_directory.stat.islnk is defined and aws_directory.stat.islnk == False

- name: Symlink aws folder to Dropbox
  file: path={{ home_directory }}/.aws src={{ home_directory }}/Dropbox/secrets/.aws state=link
